version: "3"
services:
  postgres:
    image: postgres:15.1
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

networks:
  postgres:
    driver: bridge