version: "3"
services:
  postgres:
    image: postgres:15.1
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  nestjs-api:
    container_name: api
    build:
      context: '.'
      dockerfile: .docker/node/Dockerfile
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - "3000:3000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge